PRIVATE_KEY_DEFAULT="C:\\Users\\vivek\\.ssh\\id_rsa"
read -p "Please enter PRIVATE_KEY Path [$PRIVATE_KEY_DEFAULT]: " PRIVATE_KEY
PRIVATE_KEY="${PRIVATE_KEY:-$PRIVATE_KEY_DEFAULT}"

SERVER_LOGIN_LINK_DEFAULT="root@dss-server-01.mathologic.com"
read -p "Please enter SERVER_LOGIN_LINK [$SERVER_LOGIN_LINK_DEFAULT]: " SERVER_LOGIN_LINK
SERVER_LOGIN_LINK="${SERVER_LOGIN_LINK:-$SERVER_LOGIN_LINK_DEFAULT}"

APPS_HOME_DEFAULT="~/apps"
read -p "Please enter APPS_HOME [$APPS_HOME_DEFAULT]: " APPS_HOME
APPS_HOME="${APPS_HOME:-$APPS_HOME_DEFAULT}"

APP_NAME_DEFAULT=`echo "${PWD##*/}"`
read -p "Please enter APP_NAME [$APP_NAME_DEFAULT]: " APP_NAME
APP_NAME="${APP_NAME:-$APP_NAME_DEFAULT}"

DEPLOY_TYPE_DEFAULT="stage1"
read -p "Please enter DEPLOY_TYPE [$DEPLOY_TYPE_DEFAULT]: " DEPLOY_TYPE
DEPLOY_TYPE="${DEPLOY_TYPE:-$DEPLOY_TYPE_DEFAULT}"

DEPLOY_PORT_DEFAULT="4000"
read -p "Please enter DEPLOY_PORT [$DEPLOY_PORT_DEFAULT]: " DEPLOY_PORT
DEPLOY_PORT="${DEPLOY_PORT:-$DEPLOY_PORT_DEFAULT}"

SOURCE_APP_DIR_DEFAULT="$APP_NAME.zip"
read -p "Please enter SOURCE_APP_DIR Path [$SOURCE_APP_DIR_DEFAULT]: " SOURCE_APP_DIR
SOURCE_APP_DIR="${SOURCE_APP_DIR:-$SOURCE_APP_DIR_DEFAULT}"

UTILS_DIR_DEFAULT="utils"
read -p "Please enter UTILS_DIR Path [$UTILS_DIR_DEFAULT]: " UTILS_DIR
UTILS_DIR="${UTILS_DIR:-$UTILS_DIR_DEFAULT}"

LOCAL_SH_DEFAULT="deploy-local.sh"
read -p "Please enter REMOTE_SH Path $UTILS_DIR/[$LOCAL_SH_DEFAULT]: " LOCAL_SH
LOCAL_SH="${LOCAL_SH:-$LOCAL_SH_DEFAULT}"

REMOTE_SH_DEFAULT="deploy-remote.sh"
read -p "Please enter REMOTE_SH Path $UTILS_DIR/[$REMOTE_SH_DEFAULT]: " REMOTE_SH
REMOTE_SH="${REMOTE_SH:-$REMOTE_SH_DEFAULT}"

RUN_BIN_DEFAULT="npm"
read -p "Please enter RUN_BIN Path [$RUN_BIN_DEFAULT]: " RUN_BIN
RUN_BIN="${RUN_BIN:-$RUN_BIN_DEFAULT}"

RUN_ARGS_DEFAULT="\"start PORT=$DEPLOY_PORT\""
read -p "Please enter RUN_ARGS Path [$RUN_ARGS_DEFAULT]: " RUN_ARGS
RUN_ARGS="${RUN_ARGS:-$RUN_ARGS_DEFAULT}"


BASE_LOCATION="$APPS_HOME/$APP_NAME/$DEPLOY_TYPE"

echo "> Running LOCAL_SH ($LOCAL_SH)"
sh $UTILS_DIR/$LOCAL_SH 2>&1

echo "> Making $BASE_LOCATION Directory if not existing."
ssh -i $PRIVATE_KEY $SERVER_LOGIN_LINK "mkdir -p $BASE_LOCATION"

echo "> Coping UTILS_DIR ($UTILS_DIR) to Remote server base location ($SERVER_LOGIN_LINK:$BASE_LOCATION)"
scp -i $PRIVATE_KEY -r $UTILS_DIR $SERVER_LOGIN_LINK:$BASE_LOCATION

echo "> Coping SOURCE_APP_DIR ($SOURCE_APP_DIR) to Remote server base location ($SERVER_LOGIN_LINK:$BASE_LOCATION)"
scp -i $PRIVATE_KEY -r $SOURCE_APP_DIR $SERVER_LOGIN_LINK:$BASE_LOCATION

echo "> Running REMOTE_SH ($SERVER_LOGIN_LINK:$BASE_LOCATION/$UTILS_DIR/$REMOTE_SH)"
echo "      > sh $UTILS_DIR/$REMOTE_SH $APP_NAME $DEPLOY_TYPE $BASE_LOCATION $RUN_BIN $RUN_ARGS"
ssh -i $PRIVATE_KEY $SERVER_LOGIN_LINK "cd $BASE_LOCATION;sh $UTILS_DIR/$REMOTE_SH $APP_NAME $DEPLOY_TYPE $DEPLOY_PORT $BASE_LOCATION $RUN_BIN $RUN_ARGS" 2>&1


read -p "EVERY THING RAN SUCCESSFULLY " RESULT